### ISSUE TITLE
Generating .h header file without Unico GUI

### ISSUE THREAD

**Issue by Ashment** [STMicroelectronics/STMems_Machine_Learning_Core#13]
Hello,

I was wondering if there is existing functionality for generating .h file for use with the standard C drivers. The mlc_configurator.py file appears to not provide this functionality. Is there a way to invoke Unico to do this through python instead of through the GUI, or would I need to write my own wrapper for converting .ucf into a corresponding .h file? 

Thanks for any help.

**Comment by michelefer** [comment]
Hello, 
at the moment we support the conversion from .ucf to .h file in Unico-GUI only. 
We are considering to extend this feature through python script in future releases.
