### ISSUE TITLE
About the sensor lsm6dso32x

### ISSUE THREAD

**Issue by Jiabin-develop** [STMicroelectronics/STMems_Machine_Learning_Core#5]
Just want to know, is it possible to use the MLC configuration of lsm6dsox on the lsm6dso32x.
Is there anything that I should to modify?

Thanks!

**Comment by michelefer** [comment]
No, it is not ok to use MLC configurations of LSM6DSOX in LSM6DSO32X.

**Comment by Jiabin-develop** [comment]
Thank you very much for your reply!
Could you please let me know, is there a MLC configuration example for LSM6DSO32X?
Currently, I want to implement the LSM6DSO32X sensor to recognize human's sleep, could you please provide me some guide about how to achieve that?

**Comment by Jiabin-develop** [comment]
> No, it is not ok to use MLC configurations of LSM6DSOX in LSM6DSO32X.

Thank you very much for your reply!
Could you please let me know, is there a MLC configuration example for LSM6DSO32X?
Currently, I want to implement the LSM6DSO32X sensor to recognize human's sleep, could you please provide me some guide about how to achieve that?

**Comment by michelefer** [comment]
The MLC configuration procedure for LSM6DSO32X is similar to other devices: data logging, labeling, building decision tree, etc…
You can use Unico-GUI selecting the device: STEVAL-MKI221V1 (LSM6DSO32X) and configure LSM6DSO32X in a similar way as it is described for LSM6DSOX.
For other questions, please check also https://community.st.com/
