### ISSUE TITLE
MLC configuration for LSM6DSO32X

### ISSUE THREAD

**Issue by Jiabin-develop** [STMicroelectronics/STMems_Machine_Learning_Core#6]
Very appreicate your help!
Could you please let me know, is there a MLC configuration example for LSM6DSO32X?
Currently, I want to implement the LSM6DSO32X sensor to recognize human's sleep, could you please give me some guide about how to achieve that?

**Comment by michelefer** [comment]
The MLC configuration procedure for LSM6DSO32X is similar to other devices: data logging, labeling, building decision tree, etc…
You can use Unico-GUI selecting the device: STEVAL-MKI221V1 (LSM6DSO32X) and configure LSM6DSO32X in a similar way as it is described for LSM6DSOX.
For other questions, please check also https://community.st.com/
