### ISSUE TITLE
Support for mlc_python_script with macOS

### ISSUE THREAD

**Issue by metanav** [STMicroelectronics/STMems_Machine_Learning_Core#7]
Does the mlc_python_script work with macOS? I found the code is using unico.exe which is for Windows. I have installed Unico GUI on macOS but how can we provide path for it in the script. Also,  a Windows specific python module is being using in the notebook which I think only for version check and can be ignored but what is the supported Unico version for macOS.

**Comment by michelefer** [comment]
The mlc_python_script example is for Windows, as it has been tested mainly on this platform. However, the file "external_tools.py" can be modified to make the script working on MacOS as well.
